on:
  workflow_dispatch:
    inputs:
      repoOrg:
        description: "Repo Org"
        required: true
        default: "pomber"
      repoName:
        description: "Repo Name"
        required: true
        default: "didact"
      starCount:
        description: "Star Count"
        required: true
        default: 100
      duration:
        description: "Duration (seconds)"
        required: false
        default: 15
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run build -- --props="$WORKFLOW_INPUT"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
          REMOTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out.mp4
